language: rust
cache: cargo

rust:
  - nightly

env:
  - TEST_COMMAND=test EXTRA_FLAGS='' FEATURES=''
  # Disabled for now along with the yoloproofs feature.
  #- TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='yoloproofs'
  # run cargo bench with a filter that matches no benchmarks.
  # this ensures the benchmarks build but doesn't run them on the CI server.
  - TEST_COMMAND=bench EXTRA_FLAGS='"DONTRUNBENCHMARKS"' FEATURES=''

matrix:
  include:
  - rust: nightly-2018-12-04
    before_script:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt --all -- --check

script:
  - cargo $TEST_COMMAND --features="$FEATURES" $EXTRA_FLAGS

notifications:
  slack:
    rooms:
      - dalek-cryptography:Xxv9WotKYWdSoKlgKNqXiHoD#dalek-bots
